[tool.poetry]
name = "rag-langchain-hana-example"
version = "0.1.0"
description = ""
authors = ["I574161 <yu.xuan.lee@sap.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
